package com.adeeb.autorep;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.telephony.SmsManager;
import android.telephony.TelephonyManager;
import android.widget.Toast;

public class Call_Receiver extends BroadcastReceiver{
	
	String add_num = "";
	String response = "--autogenerated msg--\n" +
					  "I am not available. I" +
					  " will contact you as soon" +
					  " as possible."+add_num+"\n~";
	
	@Override
	public void onReceive(Context arg0, Intent arg1) {
		
		Toast.makeText(arg0, "Hello World", Toast.LENGTH_LONG).show();
		int state = Main_screen.tm.getCallState();
		switch(state){
		case TelephonyManager.CALL_STATE_IDLE:
			if (Main_screen.missed_call>0){
				Toast.makeText(arg0, "Missed call", Toast.LENGTH_LONG).show();
				++Main_screen.num_missed_calls;
				//if there are five calls
				if (Main_screen.num_missed_calls>=1){
					
					Toast.makeText(arg0, "hello:"+Main_screen.other_num, Toast.LENGTH_LONG).show();
					
				//	if (Main_screen.other_num!=""){
				//		add_num = " ,contact "+Main_screen.other_num+" in case of emegency ";
				//	}
					//retreiving incoming number
					Bundle info = arg1.getExtras();
					String number = info.getString("incoming_number");
					
					//send response
					String cell_num = Main_screen.tm.getLine1Number();
					SmsManager sm = SmsManager.getDefault();
					sm.sendTextMessage(number, null, response+(Main_screen.username), null, null);
					
					//reset number of missed calls
					Main_screen.num_missed_calls = 0;
				}
			}
			Main_screen.missed_call = 0;
			break;
		case TelephonyManager.CALL_STATE_OFFHOOK:
			//answered
			Toast.makeText(arg0, "offhook", Toast.LENGTH_LONG).show();
			--Main_screen.missed_call;
			break;
		case TelephonyManager.CALL_STATE_RINGING:
			//ringing
			Toast.makeText(arg0, "ringing", Toast.LENGTH_LONG).show();
			++Main_screen.missed_call;
			break;
		}
	}
}
